'use client'

import { useState } from 'react'
import type { FileChange } from '@/lib/github/types'

interface PushDialogProps {
  repo: string
  baseBranch: string
  stagedChanges: FileChange[]
  onPush: (params: {
    repo: string
    baseBranch: string
    newBranch: string
    files: Array<{ path: string; content: string }>
    message: string
  }) => Promise<{ success: boolean; branchUrl?: string; error?: string }>
  onClose: () => void
}

export function PushDialog({ repo, baseBranch, stagedChanges, onPush, onClose }: PushDialogProps) {
  const [branchName, setBranchName] = useState(`claude/${Date.now()}`)
  const [commitMessage, setCommitMessage] = useState('feat: changes generated by Claude')
  const [pushing, setPushing] = useState(false)
  const [result, setResult] = useState<{ success: boolean; branchUrl?: string; error?: string } | null>(null)

  const handlePush = async () => {
    if (!branchName.trim() || !commitMessage.trim() || pushing) return
    setPushing(true)
    setResult(null)
    try {
      const res = await onPush({
        repo,
        baseBranch,
        newBranch: branchName.trim(),
        files: stagedChanges.map((c) => ({ path: c.path, content: c.content })),
        message: commitMessage.trim(),
      })
      setResult(res)
    } catch {
      setResult({ success: false, error: 'Push failed' })
    } finally {
      setPushing(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div
        role="dialog"
        aria-label="ブランチにプッシュ"
        className="bg-[var(--surface)] border border-[var(--border)] rounded-lg shadow-xl w-full max-w-md mx-4"
      >
        <div className="px-4 py-3 border-b border-[var(--border)]">
          <h3 className="text-sm font-semibold text-[var(--foreground)]">新しいブランチにプッシュ</h3>
          <p className="text-xs text-[var(--text-muted)] mt-0.5">
            {repo} — ベース: {baseBranch}
          </p>
        </div>

        <div className="px-4 py-3 space-y-3">
          <div>
            <label className="block text-xs text-[var(--text-muted)] mb-1">ブランチ名</label>
            <input
              type="text"
              value={branchName}
              onChange={(e) => setBranchName(e.target.value)}
              disabled={pushing || result?.success === true}
              className="w-full px-2.5 py-1.5 text-sm bg-[var(--background)] border border-[var(--border)] rounded text-[var(--foreground)] outline-none disabled:opacity-50"
            />
          </div>

          <div>
            <label className="block text-xs text-[var(--text-muted)] mb-1">コミットメッセージ</label>
            <input
              type="text"
              value={commitMessage}
              onChange={(e) => setCommitMessage(e.target.value)}
              disabled={pushing || result?.success === true}
              className="w-full px-2.5 py-1.5 text-sm bg-[var(--background)] border border-[var(--border)] rounded text-[var(--foreground)] outline-none disabled:opacity-50"
            />
          </div>

          <div className="text-xs text-[var(--text-muted)]">
            {stagedChanges.length} ファイルをプッシュ
          </div>

          {result && (
            <div
              className={[
                'text-xs px-2.5 py-2 rounded',
                result.success
                  ? 'bg-green-50 dark:bg-green-950 text-green-700 dark:text-green-400'
                  : 'bg-red-50 dark:bg-red-950 text-red-700 dark:text-red-400',
              ].join(' ')}
            >
              {result.success ? (
                <span>
                  プッシュ成功！{' '}
                  {result.branchUrl && (
                    <a
                      href={result.branchUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="underline underline-offset-2"
                    >
                      ブランチを表示
                    </a>
                  )}
                </span>
              ) : (
                <span>エラー: {result.error}</span>
              )}
            </div>
          )}
        </div>

        <div className="px-4 py-3 border-t border-[var(--border)] flex items-center justify-end gap-2">
          <button
            onClick={onClose}
            className="px-3 py-1.5 text-xs text-[var(--text-muted)] hover:text-[var(--foreground)] rounded hover:bg-[var(--surface-hover)] transition-colors"
          >
            {result?.success ? '閉じる' : 'キャンセル'}
          </button>
          {!result?.success && (
            <button
              onClick={handlePush}
              disabled={pushing || !branchName.trim() || !commitMessage.trim()}
              className="px-3 py-1.5 text-xs font-medium text-white bg-blue-600 rounded hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {pushing ? 'プッシュ中...' : 'プッシュ'}
            </button>
          )}
        </div>
      </div>
    </div>
  )
}
